### ISSUE TITLE
Errors in help file for [midifile] object

### ISSUE THREAD

**Issue by dfkettle** [pd-externals/midifile#4] opened 2022-04-18 12:15 UTC
Errors in help file: the [route_events] subpatch of [midifile_read] shows CC messages as being in the range of 176 to 192 inclusive, but 192 is a Program Change message. Also, any messages except Note On, Note Off, Control Change and System Exclusive messages are considered System messages. So Aftertouch, Channel Pressure, Pitch Bend, Channel Mode, etc., aren't being routed properly. It's not clear to me whether or not these messages are actually being written to an output file, I haven't looked at the source code very closely. But IMHO, the help file should indicate whether or not they're supported.

![162739345-7bd92fa1-0604-4d78-8701-bca6335e9dad](https://user-images.githubusercontent.com/8409615/163806715-bc1b7b6c-aa28-4a45-8554-ce7f7bfe28a5.jpg)

**Comment by umlaeute** [comment] 2022-06-01 13:07
>  There is only one small issue with Channel Pressure and Pitch Bend, which will be corrected soon, I think.

@Josef-N which "small issue"? i can't see any bug-report [here](https://github.com/pd-externals/midifile/issues). am i missing something?

**Comment by danomatika** [comment] 2022-06-01 13:09
This sentence is missing context and refers to an issue with `[c_midiplay]` and not `[midifile]` which has since been fixed. Basically I used the status byte value ranges from midifile-help.pd which, as noted, are wrong for those types.

**Comment by Josef-N** [comment] 2022-06-01 14:47
Thanks, Dan for clarifying. I see, this sentence was quite unprecise, I have been speaking about [c_midiplay], which is fixed now. I think, it would need only a few things to improve [midifile-help]:
– correcting the range for controller events: 176 to 191
– renaming [print sys] to [print others], or something like this
– including the subpatch of Dan's [c_midiplay-help] 'pd raw midi vals'. I can put it right here, I consider it as extremely helpful. This is the content:

notes on what values are used to parse raw midi bytes inside c_midiplay

status byte + channels
128 - 143: noteoff
144 - 159: noteon
160 - 175: poly aftertouch
176 - 191: control change
192 - 207: program change
208 - 223: aftertouch
224 - 239: pitch bend
255 127 len data: Midi File Proprietary Event

(to be honest – I don’t know what the last line means, this exceeds my knowledge. I never used meta events)

**Comment by Josef-N** [comment] 2022-06-01 20:52
> 255 127 len data: Midi File Proprietary 

I found also this:
http://www.somascape.org/midi/tech/mfile.html
Meta events (status byte 0xFF)
... within a MIDI file the System Reset status byte (0xFF) is used to signify a Meta event, hence Meta events are only found in MIDI files.

But this is another universe, maybe better remove it?

**Comment by danomatika** [comment] 2023-05-16 22:25
Looking at this again and in response to the original post: yes, `[midifile]` "supports" all of those message types, in the form of spitting out the bytes, at least when reading AFAICT. Just because the help file doesn't exhaustively show *all* message types, doesn't mean they don't come out. As @Josef-N mentioned, it's just a matter of adding more filtering or at least noting which status byte number ranges are for which messages.

There *is* a bug in the help file where 192 should not be listed with the control message routing. As noted previous, 192-207 are program messages for channels 0 - 15 (or 1 - 16 in Pd's parlance).

@dfkettle This seems like a separate issue. DO you mean writing messages, not only reading. I haven't actually used `[midifile]` to write a file. >It's not clear to me whether or not these messages are actually being written to an output file, I haven't looked at the source code very closely.

**Comment by danomatika** [comment] 2023-05-16 22:30
For `[c_midiplay]` the bytes output by `[midifile]` are grouped into pairs or triplets and the status bytes are used for routing. Since the midi spec guarantees message data values fall outside the status byte ranges, it works well enough, however it may fail for system messages as I don't attempt to detect them. If I did, I would need a spigot somewhere to keep the sysex stream away from the status byte detection stream since these bytes may use more of the full byte range.

3-byte channel message detection:
<img width="625" alt="Screen Shot 2023-05-17 at 12 25 49 AM" src="https://github.com/pd-externals/midifile/assets/480637/303c2bbe-8cea-459d-9011-12cb817dc11d">

2-byte system message detection:
<img width="371" alt="Screen Shot 2023-05-17 at 12 25 53 AM" src="https://github.com/pd-externals/midifile/assets/480637/2d9ca255-53c9-4fc9-81b2-44a37c2bdea0">

**Comment by danomatika** [comment] 2023-05-16 22:38
Oh, now that I remember it, there is a further example of raw midi byte handling *included with Pd*:

* open Help -> Browser
* go to Pure Data / 7.stuff / tools / miditester.pd

This is a test patch I made when I cleaned / overhauled Pd's MIDI handling some years ago.

**Comment by danomatika** [comment] 2023-05-16 23:39
<img width="1128" alt="Screen Shot 2023-05-17 at 1 38 20 AM" src="https://github.com/pd-externals/midifile/assets/480637/2d836dc1-b525-423a-9b1b-673383b8d709">

Here is a version of the help patch with additional routing:

[midifile-help.pd.zip](https://github.com/pd-externals/midifile/files/11492847/midifile-help.pd.zip)

Please test and if it is sufficient, I can make a PR.

So far I'm able to see output from most of the message types with the files I've tried reading. The "print status bytes" toggle only controls printing for channel 1 which might make it seem like not everything is coming out, however if you print the byte output from `[midifile]` it seems to be fine.

**Comment by Josef-N** [comment] 2023-05-24 20:17
Yes, this additional routing is good. I tested the patch now – sorry for the delay. Printing is fine, but some of the events that should go to Midi devices do not work. Here is a modified version of the help patch:
[midifile-help_modified.pd.zip](https://github.com/pd-externals/midifile/files/11558423/midifile-help_modified.pd.zip)
Some event types need reordering of the message bytes.
Note events are working fine, also program change and channel aftertouch.

Here some screenshots of routings that have to be modified:
![route polytouch](https://github.com/pd-externals/midifile/assets/78230036/07e5b916-ac0a-4dcf-9069-0fb5c110ef62)
![route controller](https://github.com/pd-externals/midifile/assets/78230036/8960fc47-499e-4175-94d8-18df1b4bc2b7)
![pitch bend](https://github.com/pd-externals/midifile/assets/78230036/07cab935-8a4c-46fc-b5c3-fca5c730b871)
Pitch Bend is fine, I only added a [bendout] object, so there is also Midi output, on Channel 1 at least.

Only one more tiny little thing:
the name of the subpatch [pd route system messages 192 - 223] – is this correct? The event types are program change and channel aftertouch.
I renamed it to [pd route program & aftertouch 192 - 223], is that ok for you?

**Comment by Josef-N** [comment] 2023-05-24 21:04
good!

**Comment by Josef-N** [comment] 2023-05-25 11:58
p.s.
my knowledge of pd is sufficient for getting things to work, but I know, that I am not always using the best method. Maybe you have better ideas for rearranging the order of the numbers that are going to the midi output objects.
For instance, polytouch could also be
[$2 $1 1], [$2 $1 2] ... –> [polytouchout] (without argument for channel]

In [ctlout] the problem is, that the argument for channel is just ignored, for whatever reason. So it needs the whole package (value, ctl#, channel)

**Comment by danomatika** [comment] 2023-05-25 13:26
I think the issue with ctllout is a bug. This used to work before, I believe,but with recent Pd versions it appears to have broken.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment] 2023-05-25 14:11
Yeah, maybe try the same thing with an older version of Pd.

I had a problem with my performance setup where [c_midiplay] isforwarding ctl messages via #ctlin. Using [ctlin f f] has stopped working for some reason and I wonder if this is related…

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by Josef-N** [comment] 2023-05-25 15:12
Indeed. I am using a modified version of your [c_midiplay], only ctl messages, sent directly to ctlout (not to #ctlin). I noticed, that with each event also program change is sent, which is not present in the midi file. This happens both in current desktop version of Pd and in PdParty.
Which older version of Pd should I try? Will do it later this evening.

**Comment by Josef-N** [comment] 2023-05-25 21:36
I tried a lot of things now. There is no difference in Pd 0.53.2, 0.52-2 and 0.51-4, same result.
I found out, that [u_listlastx 2] and [pd detect message type from status byte] do not completely filter out other message types (messages with 3 bytes).
It works somehow, if I only use [u_listlastx 3] for all types, expanding the routing object to 
[route noteoff noteon polytouch ctl pgm touch bend], but that results in some duplicate events of channel aftertouch.
In my patch I just disconnected the cable to [u_listlastx 2], as I do not use pgmout and touchout.
These are the ones that make problems.

**Comment by danomatika** [comment] 2023-05-26 07:35
Ok, thanks for checking. It's not likely a problem with Pd then but maybe more the midifile output handling in my abstraction. We could move any further discussion to the rc-patches repo. I think I'll try overhauling c_midiplay to use route instead of gathering the message groups.

**Comment by danomatika** [comment] 2023-05-26 20:03
> And yes, using route seems to be more reliable.

Done. I've updated c_midiplay and seems to work in my testing.

**Comment by Josef-N** [comment] 2023-05-26 21:49
perfect – I tried the same things as before and everything works, great!

**Closed** 2024-11-24 18:24 UTC
